version: "2"
services:
  www:
    build: .
    ports:
      - "8001:80"
    volumes:
      - ./www:/var/www/html/
    networks:
      - mynetwork
    depends_on:
      - postgresql

  postgresql:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: mydatabase
    volumes:
      - ./dump:/docker-entrypoint-initdb.d

    networks:
      - mynetwork

volumes:
  persistent:

networks:
  mynetwork:
